format = """\
[ÓÇ∂](bg:#030B16 fg:#7DF9AA)\
[Û∞Äµ ](bg:#7DF9AA fg:#090c0c)\
[ÓÇ∞](fg:#7DF9AA bg:#1C3A5E)\
$time\
[ÓÇ∞](fg:#1C3A5E bg:#3B76F0)\
$directory\
[ÓÇ∞](fg:#3B76F0 bg:#FCF392)\
$git_branch\
[ÓÇ∞](fg:#FCF392 bg:#030B16)\
$character\
"""

[directory]
format = "[ $path ]($style)"
style = "fg:#E4E4E4 bg:#3B76F0"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "Óúâ Ôêò "
style = "fg:#1C3A5E bg:#FCF392"

[git_status]
format = '[$all_status]($style)'
style = "fg:#1C3A5E bg:#FCF392"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#FCF392"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = "Ôêò "

[cmd_duration]
format = "[ Ôôè $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[ ‚ûú](bold green) '
error_symbol = '[ ‚úó](#E84D44) '

[time]
disabled = false
time_format = "%R"
style = "bg:#1C3A5E fg:#8DFBD2"
format = '[ Û±ëç $time ]($style)'

[nodejs]
# Setting this will hide the "via" text
label = ""
# You can change the symbol
symbol = "‚¨¢ "
# You can change the format
format = "via [‚¨¢ \\($version\\)]($style) "
# You can change the color
style = "bold green"

[ruby]
# Setting this will hide the "via" text
label = ""
# You can change the symbol
symbol = "üíé "
# You can change the format
format = "via [$symbol\\($version\\)]($style) "
# You can change the color
style = "bold red"
